[build]
target = "avr-attiny85.json"

[target.'cfg(target_arch = "avr")']
runner = "avrdude -c usbtiny -p attiny85 -U flash:w:target/avr-attiny85/release/attiny85-test.elf"

[unstable]
build-std = ["core"]